version: '2'

services:

  command:
    image: node:8
    volumes:
      - .:/app
    working_dir: /app
    command: npm i

  server:
    image: node:8
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8888:8080
    command: node node_modules/http-server/bin/http-server app

